#!/bin/bash
## This script is under GPL v3 License (http://www.gnu.org/licenses/gpl-3.0.html).
## NWHT-V1 (Njepat Wireless Hacking Tools)
## 1 May 2013
## coded by xsan-lahci idea name for this tools >> AJ4l 13
## Tested on Backtrack 5R3 - GNOME
## Thanks To > My God , My parents , My sister and my love Nabila .. 
## Many Thanks Zee Eichel | Ikonspirasi | Cassaprodigy | Ares | All Staff Indonesian Backtrack,BlacknewbieTeam,idblackhat,codewall-SEC,cr0security,Madleets
## Greetz to : MTK | Sky_Black | Orion Hunter | ZQ@R | HaX()Rlife | phpBuGz | gunslinger_ | Mywisdom | AJ4l_13 | Fryme Joe 
zenity --warning --text "This script is under GPL v3 License >> coded by xsan-lahci"
again='y'
while  [ $again == 'y' ] || [ $again == 'Y' ];
do
clear
#Dont add anything under this code
cyan='\e[0;36m'
green='\e[0;34m'
nyala='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
item='\e[1;30m'
bah='\e[1;33m'

#dont delete/edit/change my intro!! except you are lamer/plagiarism
echo -e $bah'   _______         .__     __   ____   ________ 
   \      \__  _  _|  |___/  |_ \   \ /   /_   |   
   /   |   \ \/ \/ /  |  \   __\ \   Y   / |   |	
  /    |    \     /|   Y  \  |    \     /  |   | 
  \____|__  /\/\_/ |___|  /__| /\  \___/   |___|	
          \/            \/     \/'$red'codename : NKRI'
echo -e $red '[x]'$nyala' WELCOME on > Njepat Wireless Hacking TOols'
echo -e $red '[x]'$white 'c0ded by Xsan-Lahci'$red'    <-Author-> '$white'AJ4l_13'
echo -e $red '[x]'$white 'xsanlahci[at]gmail.com'$red' <-report bugs'
echo -e $red '[x]'$white 'http://xsanlahci.org | .tv | .wordpress.com'
echo -e $red '[x]'$nyala 'Tested On Backtrack 5R3 GNOME'
echo ""
echo -e $red'Select From Menu :'
echo -e $white"       0) Download NWHT User Guide "
echo          "       1) Cracking Wifi WPA" #Auto WPA Coded by Xsan-Lahci
echo          "       2) Cracking Wifi WPA2" #Auto WPA2 Coded by Xsan-Lahci
echo          "       3) Wireless Hacking GUI" #Coded By Xsan-Lahci
echo          "       4) WPS Hacking Tool" #Coded By Xsan-Lahci
echo          "       5) Wifi-Honey" #done
echo          "       6) Network Traffic Monitor" #Coded By Xsan-Lahci
echo          "       7) Network Stress Testing" #COded By Xsan-Lahci
echo          "       8) Network Forensics" #Auto Script COded By Xsan-Lahci
echo          "       9) Another Tools For Wireless Hacking" #Coded By Xsan-LAhci
echo          "       X) Credits & About"
echo          "       Q) Exit"
echo ""
echo -n -e $red'\033[4mNWHT\033[0m'$red '> '; tput sgr0 #insert your choice
read choose
if test $choose == '1'
 then
	sh njepat/autoWPA-ng

elif test $choose == '2'
 then
	sh njepat/autoWPA2-ng

elif test $choose == '3'
 then
	sh njepat/WGUI
	
elif test $choose == '4'
 then
	sh njepat/autoreaverX
	
elif test $choose == '5'
 then
 echo -n -e $red "Insert Your ESSID (nameFakeWifi)! : > "; tput sgr0
	read essid
 echo -n -e $red "Insert Your Channel do you want! : > "; tput sgr0
	read channelcuy
	iwconfig
 echo -n -e $red "Insert Your Interface (default wlan0)! : > "; tput sgr0
	read apaan
sh wifi_honey.sh $essid $channelcuy $apaan
	
elif test $choose == '6'
 then
	sh njepat/NTM

elif test $choose == '7'
 then
	sh njepat/xDOS
 
elif test $choose == '8'
 then
 sh njepat/autoNetworkForensics

elif test $choose == '9'
 then
 sh njepat/ATFWH

elif test $choose == 'X'
	then
	clear
zenity --info --text "DISCLAIMER: modifications, changes, or alterations to this sourcecode is acceptable, however, any public releases utilizing this code must be approved by writen this tool (xsan-lahci)
Thanks to all my friend on facebook and suport special thanks to > My God Allah | My parents | My sister | and My Girlfriend
Special Thanks for your nice ideas and help to make this tool more useful:
Zee Eichel  > You tell me about security and make me love bash programing
Ikonspirasi > Thanks For Your suport and many more :D 
Thanks To All Member and Crew IBTeam | all member and Crew indonesianblackhat
Thanks To All crew Blacknewbieteam | All Regional Indonesian Backtrack Team
Thanks For My Best Friends : Jimmyromanticdevil | GTX150 | JurankDankal | Shadowmaker | Nasa | Snail_v3n0m | Guitarisnoize | TheUndick | devilnay | lasax | Mr.Iwan.S | james0baster | cassaprodigy | junior | shendo | dr.wine | sasaka | Alp0ah | gnome selpa | sanimorpix_tux | U5hant | koecroet | THJC | Andre_Corleone | mywisdom | iyansquid | computer_geex | zasad | larcenciels | ande ande lumut | minal texas | nanokbocahkidrock | Octo Purba
madan | Arul zomb | abdee_dillah | drewc0de | nisan | 5forA | AresThehopebuster | cyberking | ainul | saka | all my friend KSL | kakus130908 | alpoah | GTX150 | amstrong | mendskin | Arfha | cod3 | Udalah | ardy | eigy | rendy | irpan | temon | turn off | joko | kambing | kahfie hudson | Pak RT | AJ4l 13 | bangdevils | d3b14n | joejoen | Pak hansip | Kodoknjepatselalu | Monox | kiddies | Andynosetrave | civil kidz | MrBs | Adhitya_DCasterX-ID | nefrit | ekawithyou | Serbian Haxor CyberWorM | Steck > And ZQ@r | cybernuxbie inj3ct0r | Cupid sh3ll Bangladesh Blackhat Team | Hax0rlif3 Madleets crew | all my friends "	
zenity --warning --text "Dont forget to report Bug >> xsanlahci[at]gmail.com"

elif test $choose == '0'
 then
	gnome-terminal --command="wget https://www.dropbox.com/s/zry7gvuqpa75vny/README.pdf"

elif test $choose == 'Q'
 then
 clear
echo -e $red '                               /T /I
                              / |/ | .-~/
                          T\ Y  I  |/  /  _
         /T               | \I  |  I  Y.-~/
        I l   /I       T\ |  |  l  |  T  /
     T\ |  \ Y l  /T   | \I  l   \    l Y
 __  | \l   \l  \I l __l  l   \      _. |
 \ ~-l   \    \  \  \\ ~\  \    . .-~   |
  \   ~-. \-.  \  \  ^._ ^. --.  /  \   |
.--~-._  ~-  \  _  ~-_.---.- ._ /._ ./ ./
 >--.  ~-.   ._  ~>--    -\\   7   7   ]
^.___~==-._    ~-{  .-~ .  \\ Y . /    |        GARUDA
 <__ ~--.  ~       /_/   \   \I  Y   : |      INDONESIA
   ^-.__           ~(_/   \   >._:   | l _____
       ^--.,___.-~-  /_/   !  \-.~---l_ /     ---.
              (_/ .  ~(   /      -~---,Y   '$white'-=b-'$red'. _)
               (_/ .  \  :           / l      c-~o \
                \ /    \.    .     .^   \_.-~~~--.  )
                 (_/ .   \  /     /       !       )/
                  / / _.   /.   ./:      /        v
                  ~(_/ .   /    _  \  .-<_
                    /_/ . / .-~- \.  / \  \          ,z=.
                    ~( /   /  :   | K   <-.~-.______//
                      \-,.    l   I/ \_    __{--->._(==.
                       //(     \  <    ~~~-     //
                      // /\     \  \     ,v=.  ((
                    .^. / /\     \  }__ //===- 
                   / / / /  /-.,__ {---(==-
                 .^ /       :  T  ~|   ll      
                / .  .  . : | :!        \\
               (_/  /   | | j-/          ~^
                 ~-<_(_.^-~/'
      exit
fi

echo
echo -e -n "Back to Menu NWHT? (y/n) :";
read again;

    while  [ $again != 'y' ] && [ $again != 'Y' ] && [ $again != 'n' ] && [ $again != 'N' ];
    do
       echo -n "Back to menu (y/n) :";
       read again;
    done
done
#DISCLAIMER: modifications, changes, or alterations to this sourcecode is acceptable, however,
#any public releases utilizing this code must be approved by writen this tool (xsan-lahci)
